name: bullet-journal
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- jupyter
- jupyterlab
- pyyaml
- flask
- python-dateutil
- humanize
- httplib2
- pip:
  - google-api-python-client
